name: NetworkBackend
version: 1.0.0
main: ru.sp0ge.Backend
api-version: '1.21'
load: STARTUP
softdepend: [AuthMe, Chunky]
commands:
  kiwypillarsresult:
    description: Internal Pillars map result bridge
  home:
    description: Teleport to your bed
  tpa:
    description: Request teleport
  tpaccept:
    description: Accept teleport request
  tpdeny:
    description: Reject teleport request
  pvp:
    description: Request a duel
  pvpaccept:
    description: Accept a duel
  pvpdeny:
    description: Reject a duel
  pvpleave:
    description: Leave a duel
  checkpoint:
    description: Return to checkpoint
  restart:
    description: Restart parkour
  arena:
    description: Control arena admission
    permission: network.arena.admin
permissions:
  network.arena.admin:
    default: op
