const mineflayer=require('mineflayer'),fs=require('fs'),crypto=require('crypto'),rcon=require('./rcon');
const token=fs.readFileSync('/secrets/api-token','utf8').trim(),rp=token;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let bots=[];
async function api(host,path,body){const r=await fetch('http://'+host+path,{headers:{Authorization:'Bearer '+token},...(body===undefined?{}:{method:'POST',body:JSON.stringify(body)}),signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error(host+path+' '+r.status);return r.json();}
async function until(check,label,timeout=120000){const t=Date.now();while(Date.now()-t<timeout){if(await check())return;await sleep(500);}throw Error('Timeout '+label);}
async function at(b,host){try{return (await api(host+':8081','/status')).players.includes(b._client.uuid)}catch{return false}}
async function join(name,password){const b=mineflayer.createBot({host:'proxy',username:name,auth:'offline',version:'1.21.10',physicsEnabled:false});bots.push(b);b.lines=[];b.on('messagestr',s=>b.lines.push(s));b.on('kicked',s=>console.log('KICK',name,JSON.stringify(s)));b.on('error',e=>console.log('ERROR',name,e.message));b._client.on('playerlist_header',p=>b.tabHeader=JSON.stringify(p));b._client.on('declare_commands',p=>b.commands=p.nodes[p.rootIndex].children.map(i=>p.nodes[i].extraNodeData.name));
const write=b._client.write.bind(b._client);b._client.write=(n,d)=>{if(['position','position_look','look'].includes(n)&&Object.entries(d).some(([k,v])=>['x','y','z','yaw','pitch'].includes(k)&&!Number.isFinite(v)))return;write(n,d);if(['position','position_look','look','flying'].includes(n))write('tick_end',{})};
await until(()=>at(b,'lobby'),'lobby '+name);await sleep(2500);if(!b.inventory.items().some(i=>i.name==='written_book'))throw Error('Missing guidebook');console.log('PASS guidebook',name);b.chat('/login '+password);await until(async()=>(await api('lobby:8081','/auth?uuid='+b._client.uuid)).authenticated,'auth');await sleep(3500);return b;}
async function route(b,target){b.chat('/server '+target);await until(()=>at(b,target),'route '+target,180000);await sleep(1500)}
const inventory=o=>JSON.stringify([o.storage,o.armor,o.extra,o.level,o.exp,o.total_exp]);
async function main(){
const a=await join('MCNetTestA',fs.readFileSync('/tests/password','utf8')),b=await join('MCNetTestB',fs.readFileSync('/tests/password-b','utf8'));
const name='MCScatter'+crypto.randomBytes(2).toString('hex'),pass=crypto.randomBytes(12).toString('hex');fs.writeFileSync('/tests/feature-account.json',JSON.stringify({name,password:pass}),{mode:0o600});await rcon('lobby',rp,'authme register '+name+' '+pass);await until(async()=>(await api('lobby:8081','/registered?name='+name)).registered,'new account');const observer=await join(name,pass);
observer.chat('/help');await until(()=>observer.lines.some(s=>s.includes('/pvpaccept')),'help');if(!observer.tabHeader?.includes('lobby'))throw Error('Missing lobby TAB');if(observer.commands?.some(c=>!['server','help','register','login','logout','changepassword'].includes(c)))throw Error('Extra commands leaked: '+observer.commands);console.log('PASS help, TAB and command tree',observer.commands);
await route(a,'survival');await route(b,'survival');await route(observer,'survival');await until(async()=>!(await api('survival:8081','/player?uuid='+observer._client.uuid)).spawning,'scatter');const area=await api('survival:8081','/spawn-area'),pos=await api('survival:8081','/player?uuid='+observer._client.uuid);if(pos.x<area.min_x||pos.x>area.max_x+1||pos.z<area.min_z||pos.z>area.max_z+1)throw Error('Scatter outside bounds');console.log('PASS scatter',pos,area);await route(observer,'lobby');await route(observer,'survival');const pos2=await api('survival:8081','/player?uuid='+observer._client.uuid);if(Math.abs(pos.x-pos2.x)+Math.abs(pos.z-pos2.z)>1)throw Error('Rejoin moved spawn');console.log('PASS rejoin keeps position');await route(observer,'lobby');
await rcon('survival',rp,'gamemode creative '+a.username);await rcon('survival',rp,'gamemode creative '+b.username);await rcon('survival',rp,'tp '+a.username+' 0 160 0');await rcon('survival',rp,'tp '+b.username+' 127 160 0');await sleep(1200);a.chat('CHAT_NEAR_127');await until(()=>b.lines.some(s=>s.includes('CHAT_NEAR_127')),'near chat');await rcon('survival',rp,'tp '+b.username+' 129 160 0');await sleep(1200);a.chat('CHAT_FAR_129');await sleep(2000);if(b.lines.some(s=>s.includes('CHAT_FAR_129')))throw Error('Far chat leaked');console.log('PASS local chat 127/129');
await route(observer,'parkour');const course=await api('parkour:8081','/parkour/status');if(course.steps.length!==81)throw Error('Parkour steps');const step=course.steps[10];await rcon('parkour',rp,'tp '+observer.username+' '+(step.x+.5)+' '+(step.y+1)+' '+(step.z+.5));await sleep(1000);observer._client.write('position',{x:step.x+.6,y:step.y+1,z:step.z+.5,flags:{onGround:true,hasHorizontalCollision:false}});await until(()=>observer.lines.some(s=>s.includes('Контрольная точка 1')),'checkpoint contact');await rcon('parkour',rp,'tp '+observer.username+' .5 101 .5');observer.chat('/checkpoint');await sleep(1000);const cp=await api('parkour:8081','/player?uuid='+observer._client.uuid);if(Math.abs(cp.x-step.x-.5)>1)throw Error('Checkpoint not retained');const newer=await api('parkour:8081','/parkour/regenerate',{});if(newer.seed===course.seed)throw Error('Seed unchanged');observer.chat('/checkpoint');await sleep(1000);const reset=await api('parkour:8081','/player?uuid='+observer._client.uuid);if(Math.abs(reset.x-.5)>1)throw Error('Regeneration did not reset checkpoint');console.log('PASS parkour generation and checkpoint');
await rcon('survival',rp,'clear '+a.username);await rcon('survival',rp,'clear '+b.username);await rcon('survival',rp,'give '+a.username+' diamond 7');await rcon('survival',rp,'give '+a.username+' cooked_beef 16');await rcon('survival',rp,'item replace entity '+a.username+' armor.chest with diamond_chestplate');await rcon('survival',rp,'item replace entity '+a.username+' weapon.offhand with shield');await rcon('survival',rp,'give '+b.username+' golden_apple 3');
const originalA=inventory(await api('survival:8081','/inventory?uuid='+a._client.uuid)),originalB=inventory(await api('survival:8081','/inventory?uuid='+b._client.uuid));a.chat('/pvp '+b.username);await until(()=>b.lines.some(s=>s.includes('вызывает вас')),'pvp request');b.chat('/pvpaccept');await until(async()=>await at(a,'pvp')&&await at(b,'pvp'),'duel join');console.log('PASS duel transfer');await sleep(4000);await rcon('pvp',rp,'clear '+a.username+' diamond');await rcon('pvp',rp,'clear '+b.username+' golden_apple');await rcon('pvp',rp,'kill '+b.username);await until(async()=>await at(a,'survival')&&await at(b,'survival'),'duel return');await sleep(2000);if(inventory(await api('survival:8081','/inventory?uuid='+a._client.uuid))!==originalA||inventory(await api('survival:8081','/inventory?uuid='+b._client.uuid))!==originalB)throw Error('Original inventory mismatch');await until(()=>observer.lines.some(s=>s.includes('Игрок '+a.username+' выиграл '+b.username+' в PVP')),'global winner parkour');console.log('PASS PvP original inventory and global winner announcement');
await route(observer,'lobby');a.chat('/pvp '+b.username);await sleep(1000);b.chat('/pvpaccept');await until(async()=>await at(a,'pvp')&&await at(b,'pvp'),'duel 2');b.quit();await until(()=>at(a,'survival'),'disconnect returns peer');if(inventory(await api('survival:8081','/inventory?uuid='+a._client.uuid))!==originalA)throw Error('Disconnect inventory mismatch');console.log('PASS disconnect return');
const rejoined=await join('MCNetTestB',fs.readFileSync('/tests/password-b','utf8'));await route(rejoined,'survival');if(inventory(await api('survival:8081','/inventory?uuid='+rejoined._client.uuid))!==originalB)throw Error('Offline inventory mismatch');console.log('PASS disconnected player inventory on rejoin');
a.chat('/pvp '+rejoined.username);await sleep(1000);rejoined.chat('/pvpaccept');await until(async()=>await at(a,'pvp')&&await at(rejoined,'pvp'),'duel crash setup');fs.writeFileSync('/tests/pvp-restart-ready','ready');await until(async()=>await at(a,'survival')&&await at(rejoined,'survival'),'PvP restart recovery',180000);if(inventory(await api('survival:8081','/inventory?uuid='+a._client.uuid))!==originalA||inventory(await api('survival:8081','/inventory?uuid='+rejoined._client.uuid))!==originalB)throw Error('Crash inventory mismatch');console.log('PASS PvP restart inventory recovery');
for(const bot of bots)bot.quit();await sleep(1500);await rcon('lobby',rp,'authme unregister '+name);console.log('FEATURES_OK');}
main().then(()=>process.exit(0)).catch(e=>{console.error(e.stack);for(const b of bots)b.quit();process.exit(1)});
