const mineflayer=require('mineflayer'),fs=require('fs'),crypto=require('crypto'),rcon=require('./rcon');
const token=fs.readFileSync('/secrets/api-token','utf8').trim(),rp=token;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let bots=[];
async function api(host,path,body){const r=await fetch('http://'+host+path,{headers:{Authorization:'Bearer '+token},...(body===undefined?{}:{method:'POST',body:JSON.stringify(body)}),signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error(host+path+' '+r.status);return r.json();}
async function until(check,label,timeout=120000){const t=Date.now();while(Date.now()-t<timeout){if(await check())return;await sleep(500);}throw Error('Timeout '+label);}
async function at(b,host){try{return (await api(host+':8081','/status')).players.includes(b._client.uuid)}catch{return false}}
async function join(name,password){const b=mineflayer.createBot({host:'proxy',username:name,auth:'offline',version:'1.21.10',physicsEnabled:false});bots.push(b);b.lines=[];b.on('messagestr',s=>b.lines.push(s));b.on('kicked',s=>console.log('KICK',name,JSON.stringify(s)));b.on('error',e=>console.log('ERROR',name,e.message));b._client.on('playerlist_header',p=>b.tabHeader=JSON.stringify(p));b._client.on('declare_commands',p=>b.commands=p.nodes[p.rootIndex].children.map(i=>p.nodes[i].extraNodeData.name));
const write=b._client.write.bind(b._client);b._client.write=(n,d)=>{if(['position','position_look','look'].includes(n)&&Object.entries(d).some(([k,v])=>['x','y','z','yaw','pitch'].includes(k)&&!Number.isFinite(v)))return;write(n,d);if(['position','position_look','look','flying'].includes(n))write('tick_end',{})};
await until(()=>at(b,'lobby'),'lobby '+name);await sleep(2500);if(!b.inventory.items().some(i=>i.name==='written_book'))throw Error('Missing guidebook');console.log('PASS guidebook',name);b.chat('/login '+password);await until(async()=>(await api('lobby:8081','/auth?uuid='+b._client.uuid)).authenticated,'auth');await sleep(3500);return b;}
async function route(b,target){b.chat('/server '+target);await until(()=>at(b,target),'route '+target,180000);await sleep(1500)}
const inventory=o=>JSON.stringify([o.storage,o.armor,o.extra,o.level,o.exp,o.total_exp]);
async function main(){
 const a=await join('MCNetTestA',fs.readFileSync('/tests/password','utf8')),b=await join('MCNetTestB',fs.readFileSync('/tests/password-b','utf8'));await route(a,'survival');await route(b,'survival');
 const oldA=inventory(await api('survival:8081','/inventory?uuid='+a._client.uuid)),oldB=inventory(await api('survival:8081','/inventory?uuid='+b._client.uuid));a.chat('/pvp '+b.username);await sleep(1000);b.chat('/pvpaccept');await until(async()=>await at(a,'pvp')&&await at(b,'pvp'),'duel');a.chat('/pvpleave');await until(async()=>await at(a,'survival')&&await at(b,'survival'),'return');await until(()=>b.lines.some(s=>s.includes('Игрок '+b.username+' выиграл '+a.username+' в PVP')),'forfeit winner');
 if(inventory(await api('survival:8081','/inventory?uuid='+a._client.uuid))!==oldA||inventory(await api('survival:8081','/inventory?uuid='+b._client.uuid))!==oldB)throw Error('Inventory differs');console.log('PASS surrender winner announcement and original inventories');for(const bot of bots)bot.quit();await sleep(1000);console.log('FORFEIT_OK');}
 main().then(()=>process.exit(0)).catch(e=>{console.error(e.stack);for(const b of bots)b.quit();process.exit(1)});
